import{a as L,S as x,i}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();const w=L.create({baseURL:"https://pixabay.com/api/",params:{key:"51736098-e561806c369733f177830f298",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function g(e,r,s=15){return(await w.get("",{params:{q:e,page:r,per_page:s}})).data}const y=document.querySelector(".gallery");let v=new x(".gallery a");function p(e){const r=e.map(s=>`<li class="gallery-item">
            <a class="gallery-link" href="${s.largeImageURL}">
            <img
            class="gallery-image"
            src="${s.webformatURL}"
            data-source="${s.largeImageURL}"
            alt="${s.tags}"
            />
            <div class = "gallery-box">
            <p class="gallery-box-text">Likes <span class="gallery-box-span">${s.likes}</span></p>
            <p class="gallery-box-text">Views <span class="gallery-box-span">${s.views}</span></p>
            <p class="gallery-box-text">Comments <span class="gallery-box-span">${s.comments}</span></p>
            <p class="gallery-box-text">Downloads <span class="gallery-box-span">${s.downloads}</span></p>
            </div>
            </a>
            </li>`).join("");y.insertAdjacentHTML("beforeend",r),v.refresh()}function S(){y.innerHTML=""}function m(){document.querySelector(".loader").classList.remove("is-hidden")}function h(){document.querySelector(".loader").classList.add("is-hidden")}function q(){document.querySelector(".btn-load").classList.remove("is-hidden")}function n(){document.querySelector(".btn-load").classList.add("is-hidden")}function b(e,r,s=15){const l=Math.ceil(e/s);r<l?q():(n(),iziToast.info({message:"We're sorry, but you've reached the end of search results."}))}function $(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}const E=document.querySelector(".form"),M=document.querySelector(".btn-load");let c="",o=1;const f=15;let d=0;E.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements.searchText.value.trim(),c===""){i.warning({title:"Warning",message:"Empty input field"});return}o=1,S(),m(),n();try{const r=await g(c,o,f);if(d=r.totalHits,r.hits.length===0){n(),i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}else p(r.hits),b(d,o),e.target.reset()}catch{n(),i.error({message:"An error occurred while fetching images. Please try again."})}finally{h()}});M.addEventListener("click",async()=>{o+=1,m(),n();try{const e=await g(c,o,f);p(e.hits),b(d,o),$(),o*f>=d&&(i.info({message:"You have reached the end of search results."}),n())}catch{i.error({message:"An error occurred while fetching images. Please try again."})}finally{h()}});
//# sourceMappingURL=index.js.map
